server:
  port: 8082
  shutdown: graceful

spring:
  config:
    import: classpath:oauth-google-client.yaml
  application:
    name: spring-oauth2-client
  cloud:
    gateway:

      server:
        webflux:
          default-filters:
            - SaveSession
            - TokenRelay
          routes:
            - id: spring-resource-server
              uri: ${RESOURCE_SERVER:http://localhost:8080}/spring-resource-server/
              predicates:
                - Path=/spring-resource-server/**

logging:
  level:
    org:
      springframework:
        web:
          HttpLogging: trace
        security : DEBUG